# -*- coding: utf-8 -*-
"""Histopathologic Cancer (Kaggle).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IF29XBEHdVpUC22zrGE_lrUSafqbL-wf
"""

from google.colab import files
files.upload()

!pip install fastai
!pip install kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle competitions download -c histopathologic-cancer-detection

from fastai.vision import *

!ls

!unzip -q train.zip -d train
!rm train.zip
!unzip -q train_labels.csv.zip

ds_tfms=get_transforms(do_flip=True, flip_vert=True, max_lighting=0.1, max_warp=0.)
data = ImageDataBunch.from_csv('', folder='train', size=112, suffix='.tif', csv_labels='train_labels.csv', test = 'test')
data.normalize()

pd.read_csv('train_labels.csv').head()

#learn = create_cnn(data, models.resnet101, metrics=[accuracy])
learn = create_cnn(data, models.densenet121, metrics=[accuracy])

learn.fit_one_cycle(5)

learn.save('freez')

learn.unfreeze()
learn.lr_find()
learn.recorder.plot()

learn.fit_one_cycle(2, max_lr=slice(1e-06,1e-05))

print(learn.summary())

